[project]
name = "openbis-upload-helper"
version = "0.1.0"
description = "Desktop helper for parsing and uploading scientific data to openBIS."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bam-masterdata>=0.12.0",
    "pybis>=1.37.5",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
    "ruff>=0.16.6",
]

[project.scripts]
openbis-upload-helper = "openbis_upload_helper:main.main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "python"